[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "totalordering"
version = "0.1.0"
dependencies = [
    "django>=3.2,<4",
    "gunicorn",
    "mysqlclient"
]
