# Generated by Django 3.2.25 on 2024-04-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.CharField(max_length=14, primary_key=True, serialize=False)),
            ],
        ),
    ]
